---
title: "Untitled"
format: html
editor: visual
---

```{r message = F, warning = F}
library(tidyverse)
```


```{r}
data <- readRDS("../data/data_ye2.RData")%>% 
  rename_all(~str_replace(.,"2","")) %>% 
  filter(SOURCE == "Kansas")


mod <- readRDS("../output/model/summaries_50M.RData") %>% 
  filter(CLEAN == "Moderate")
mod$mod_sum[[1]]
```


```{r}
valid <- 
readxl::read_excel("../data/validation.xlsx", sheet = "Metric_units") %>% 
  transmute(.,
         ENV = ENV,
         TRT = ifelse(Seed_Trt == "Control","None", Seed_Trt),
         STAND =  as.double(`Population_plants/m2`), 
         YIELD = as.double(`Yield_kg/ha`)/1000
         ) %>% 
  drop_na(YIELD, STAND) %>% 
  # get the yielding environment grouping
  nest() %>% 
  mutate(.,
         km = map(data, function(data){
           # Clustering vector
           cvec <- kmeans(data$YIELD, centers = 2)[["cluster"]]
           # Define high and low cat
           cvec <- ifelse(cvec == 1, "Low", "High")
           return(cvec)
           
           }
                  )
         ) %>% 
  unnest(cols = c(data,km)) %>% 
  mutate(.,
         YE = case_when(ENV %in% c("BV19", "GB18","HT19", "LT19","MH19")~"5.59", T~"3.37")
         )
         )

valid

valid %>% 
  unnest() %>% 
ggplot(aes(x = STAND, y = YIELD, color = TRT))+
  geom_point()+
  facet_wrap(~YE)
```


```{r}
obs <- valid %>% 
  filter(TRT == "None", YE == "3.37") %>% 
  mutate(STAND = round(STAND,0) ) %>% 
  filter(STAND %in% c(round(preds$STAND,0)))
  
  # group_by(STAND) %>% 
  # summarise(YIELD = mean(YIELD))
# low none moderate preds

preds <- mod$mod_sum[[1]] %>% 
  filter(STAND %in% c(round(obs$STAND,0)))



plot(preds$pred_q500, obs$YIELD)
```

